/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GomokuTableStatus {
  table_id: number
  state: 0 | 1 | 2 | 100 | 101 | 102 | 200 | 300 | 301
  player1: User
  player2: User
  left_is_black: boolean
  queue: User[]
  moves: Move[]
}
export interface User {
  user_id: number
  user_name: string
}
export interface Move {
  x: number
  y: number
}
