# generated by datamodel-codegen:
#   filename:  gomoku.json
#   timestamp: 2022-04-14T09:15:33+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Extra


class User(BaseModel):
    class Config:
        extra = Extra.forbid

    user_id: int
    user_name: str


class Move(BaseModel):
    class Config:
        extra = Extra.forbid

    x: int
    y: int


class TableState(Enum):
    IDLE = 'IDLE'
    P1S = 'P1S'
    P2S = 'P2S'
    BS = 'BS'
    BS_P1R = 'BS_P1R'
    BS_P2R = 'BS_P2R'
    PLAYING = 'PLAYING'
    C_P1W = 'C_P1W'
    C_P2W = 'C_P2W'


class GomokuTableStatus(BaseModel):
    class Config:
        extra = Extra.forbid

    table_id: int
    state: TableState
    player1: Optional[User] = None
    player2: Optional[User] = None
    left_is_black: bool
    queue: List[User]
    moves: List[Move]
