# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2022-04-14T09:15:34+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class User(BaseModel):
    class Config:
        extra = Extra.forbid

    user_id: int
    user_name: str
